name: Mise à jour Veille 7h00

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update-veille:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Préparer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Installer Feedparser
        run: pip install feedparser
        
      - name: Exécuter le script
        run: python Veille_tech_json.py
        
      - name: Sauvegarder le résultat
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bot Veille"
          git add veille.json
          git commit -m "MAJ Automatique de la veille" || echo "Rien à mettre à jour"
          git push
