name: Mise à jour Veille 7h00

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

# On force les droits d'écriture pour être sûr à 100%
permissions:
  contents: write

jobs:
  update-veille:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Préparer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Installer Feedparser
        run: pip install feedparser
        
      - name: Exécuter le script
        run: python Veille_tech_json.py
        
      # On remplace tes commandes Git manuelles par ce plugin "bulldozer"
      - name: Sauvegarder le résultat
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "MAJ Automatique de la veille"
          file_pattern: 'veille.json'
